import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  ach = 'https://en.wikipedia.org/wiki/Automated_clearing_house';
  api = 'https://246gg84zg8.execute-api.us-west-2.amazonaws.com/prod/projects';
  ai = 'https://en.wikipedia.org/wiki/Artificial_intelligence';
  agile = 'https://en.wikipedia.org/wiki/Agile_software_development';
  book = 'https://books.google.com/books/about/Estandarización_y_mejora_de_procesos_y.html?id=ipI3HQAACAAJ';
  bug = 'https://en.wikipedia.org/wiki/Software_bug';
  career = 'https://en.wikipedia.org/wiki/Career_development';
  ccp = 'https://aws.amazon.com/certification/certified-cloud-practitioner/';
  central = 'https://en.wikipedia.org/wiki/Central_Time_Zone';
  chicago = 'https://en.wikipedia.org/wiki/Chicago';
  clientFacing = 'https://en.wikipedia.org/wiki/Client-facing';
  codeReview = 'https://en.wikipedia.org/wiki/Code_review';
  coursera = 'https://www.coursera.org/specializations/deep-learning';
  data = 'https://en.wikipedia.org/wiki/Data_science';
  dependencyInjection = 'https://en.wikipedia.org/wiki/Dependency_injection';
  deployments = 'https://en.wikipedia.org/wiki/Software_deployment';
  devops = 'https://en.wikipedia.org/wiki/DevOps';
  django = 'https://youtu.be/QjrfUO91wfc';
  dojo1 = 'https://www.codingdojo.com/onsite-boot-camp';
  dojo2 = 'https://www.codingdojo.com/data-science-ml-python-bootcamp';
  echo = 'https://www.echo.com/';
  echodrive = 'https://echodrive.com';
  echoship = 'https://echoship.com';
  eft = 'https://en.wikipedia.org/wiki/Electronic_funds_transfer';
  ehr = 'https://en.wikipedia.org/wiki/Electronic_health_record';
  feature = 'https://en.wikipedia.org/wiki/Feature_toggle';
  feedback = 'https://en.wikipedia.org/wiki/360-degree_feedback';
  frontEnd = 'https://en.wikipedia.org/wiki/Front-end_web_development';
  guestimate = 'https://en.wikipedia.org/wiki/Guesstimate';
  grooming = 'https://en.wikipedia.org/wiki/Scrum_(software_development)#Backlog_refinement';
  hacker = 'https://www.hackerrank.com/mruanova';
  header = 'Mauricio Ruanova';
  image = 'https://mruanova.com/mau.png';
  iso = 'https://en.wikipedia.org/wiki/International_Organization_for_Standardization';
  kaggle = 'https://kaggle.com/mruanova';
  launchdarkly = 'https://launchdarkly.com';
  lerna = 'https://github.com/lerna/lerna';
  linkedin = 'https://www.linkedin.com/in/mruanova/';
  machine = 'https://en.wikipedia.org/wiki/Machine_learning';
  mel = 'https://en.wikipedia.org/wiki/Microsoft_Enterprise_Library';
  methodology = 'https://en.wikipedia.org/wiki/Software_development_process';
  microsoft = 'https://docs.microsoft.com/en-us/learn/certifications/exams/70-480';
  microservices = 'https://en.wikipedia.org/wiki/Microservices';
  nearshore = 'https://en.wikipedia.org/wiki/Outsourcing#Nearshoring';
  net = 'https://en.wikipedia.org/wiki/.net';
  node = 'https://nodejs.org/en/';
  offshore = 'https://en.wikipedia.org/wiki/Offshoring';
  oidc = 'https://github.com/IdentityModel/oidc-client-js';
  paper = 'https://link.springer.com/chapter/10.1007/11499053_28/';
  perfomanceAppraisal = 'https://en.wikipedia.org/wiki/Performance_appraisal';
  releases = 'https://en.wikipedia.org/wiki/Software_release_life_cycle';
  react = 'https://reactjs.org';
  rollup = 'https://www.npmjs.com/package/rollup';
  sops = 'https://github.com/mozilla/sops';
  stackoverflow = 'https://stackoverflow.com/users/5490782/mruanova/';
  storybook = 'https://github.com/storybookjs/storybook/';
  tms = 'https://tms.echo.com';
  tutorial = 'https://youtu.be/v7-MZkz-3BE';
  retro = 'https://en.wikipedia.org/wiki/Scrum_(software_development)#Sprint_retrospective';
  quality = 'https://en.wikipedia.org/wiki/Software_quality';
  saas = 'https://en.wikipedia.org/wiki/Software_as_a_service';
  serverless = 'https://en.wikipedia.org/wiki/Serverless_computing';
  signage = 'https://en.wikipedia.org/wiki/Digital_signage';
  snippets = 'https://mruanova.com/snippets.html';
  softSkills = 'https://en.wikipedia.org/wiki/Soft_skills';
  softwareArchitecture = 'https://en.wikipedia.org/wiki/Software_architecture';
  softwareEngineer = 'https://en.wikipedia.org/wiki/Software_engineering';
  solid = 'https://en.wikipedia.org/wiki/SOLID';
  sonarQube = 'https://en.wikipedia.org/wiki/SonarQube';
  sprintPlanning = 'https://en.wikipedia.org/wiki/Scrum_(software_development)#Sprint_planning';
  stakeholders = 'https://en.wikipedia.org/wiki/Project_stakeholder';
  standUp = 'https://en.wikipedia.org/wiki/Stand-up_meeting';
  shoplocal = 'https://shoplocal.com/?postalcode=60670';
  swift = 'https://en.wikipedia.org/wiki/SWIFT_message_types';
  tableau = 'https://public.tableau.com/profile/mruanova';
  teamLeader = 'https://en.wikipedia.org/wiki/Team_leader';
  test = 'https://en.wikipedia.org/wiki/Test_automation';
  time = 'https://en.wikipedia.org/wiki/Time_management';
  timeZone = 'https://en.wikipedia.org/wiki/Time_zone';
  title = 'Hola!';
  udem = 'https://www.udem.edu.mx/itc';
  udemy = 'https://www.udemy.com/course/aws-certified-solutions-architect-associate/';
  underwriting = 'https://en.wikipedia.org/wiki/Underwriting';
  unit = 'https://en.wikipedia.org/wiki/Unit_testing';
  youtube = 'https://www.youtube.com/channel/UC_HW27YMfrpQeX1v5AijWSQ?sub_confirmation=1';
}
